services:
  nginx:
    image: nginx:alpine
    container_name: nginx-sem1
    ports:
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
